### ISSUE TITLE
HTTP 404 error in docs

### ISSUE THREAD

**Issue by mmc46** [natverse/hemibrainr#47]
Clicking on an article points to a 404 error, `articles/` is added to the url and the link doesn't resolve, or not pointing to the right place.
in this case I clicked once for each the first 3 articles, all with 404 errors.

![Screenshot 2021-05-10 at 11 58 55](https://user-images.githubusercontent.com/1872083/117649501-7ebdc780-b187-11eb-9e44-a97fe25c687c.png)
![Screenshot 2021-05-10 at 11 59 06](https://user-images.githubusercontent.com/1872083/117649512-81202180-b187-11eb-8d2e-ec5de166e7a0.png)

**Comment by jefferis** [comment]
Thanks for this @mmc46. I am closing as this doesn't seem to be the case at present. Please reopen if you still see an issue.
